const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
const SAVE_SAVE_SHOPPING = 'SAVE_SAVE_SHOPPING';

export {
    ADD_TO_CART,
    REMOVE_ITEM_CART,
    SAVE_SAVE_SHOPPING

    
  };
  