const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST';
const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS';
const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL';

const PRODUCTS_DETAIL_REQUEST = 'PRODUCTS_DETAIL_REQUEST';
const PRODUCTS_DETAIL_SUCCESS = 'PRODUCTS_DETAIL_SUCCESS';
const PRODUCTS_DETAIL_FAIL = 'PRODUCTS_DETAIL_FAIL';

const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';

const CLEAR_ERROS = 'CLEAR_ERROS';


export {
  ALL_PRODUCTS_REQUEST,
  ALL_PRODUCTS_SUCCESS,
  ALL_PRODUCTS_FAIL,
  CLEAR_ERROS,
  PRODUCTS_DETAIL_REQUEST,
  PRODUCTS_DETAIL_SUCCESS,
  PRODUCTS_DETAIL_FAIL,
  NEW_REVIEW_REQUEST,
  NEW_REVIEW_SUCCESS,
  NEW_REVIEW_RESET,
  NEW_REVIEW_FAIL,
  ADMIN_PRODUCTS_REQUEST,
  ADMIN_PRODUCTS_SUCCESS,
  ADMIN_PRODUCTS_FAIL

};
