const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCES = 'REGISTER_USER_SUCCES';
const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';


const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCES = 'UPDATE_USER_SUCCES';
const UPDATE_USER_RESET = 'UPDATE_USER_RESET';
const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
const UPDATE_PASSWORD_SUCCES = 'UPDATE_PASSWORD_SUCCES';
const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET';
const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
const LOAD_USER_SUCCES = 'LOAD_USER_SUCCES';
const LOAD_USER_FAIL = 'LOAD_USER_FAIL';


const LOGOUT_USER_SUCCES = 'LOGOUT_USER_SUCCES';
const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
const CLEAR_ERROS = 'CLEAR_ERROS';


export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    CLEAR_ERROS,
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCES,
    REGISTER_USER_FAIL,
    LOAD_USER_REQUEST,
    LOAD_USER_SUCCES,
    LOAD_USER_FAIL,
    LOGOUT_USER_SUCCES,
    LOGOUT_USER_FAIL,
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCCES,
    UPDATE_USER_FAIL,
    UPDATE_PASSWORD_REQUEST,
    UPDATE_PASSWORD_SUCCES,
    UPDATE_PASSWORD_RESET,
    UPDATE_PASSWORD_FAIL,
    UPDATE_USER_RESET
};
